.TH "Try2/gam.h" 3 "Thu Nov 30 2023" "Project Paper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Try2/gam.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUP\fP   1"
.br
.ti -1c
.RI "#define \fBDOWN\fP   \-1"
.br
.ti -1c
.RI "#define \fBRIGHT\fP   2"
.br
.ti -1c
.RI "#define \fBLEFT\fP   \-2"
.br
.ti -1c
.RI "#define \fBMAX\fP   60"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitGrid\fP (int, int)"
.br
.ti -1c
.RI "void \fBdrawGrid\fP ()"
.br
.ti -1c
.RI "void \fBdrawSnake\fP ()"
.br
.ti -1c
.RI "void \fBdrawfood\fP ()"
.br
.ti -1c
.RI "void \fBrandom\fP (int &, int &)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DOWN   \-1"

.SS "#define LEFT   \-2"

.SS "#define MAX   60"

.SS "#define RIGHT   2"

.SS "#define UP   1"

.SH "Function Documentation"
.PP 
.SS "void drawfood ()"

.SS "void drawGrid ()"

.SS "void drawSnake ()"

.SS "void initGrid (int x, int y)"

.SS "void random (int & x, int & y)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Paper from the source code\&.
