.TH "Try2/new_st.cpp" 3 "Thu Nov 30 2023" "Project Paper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Try2/new_st.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <GL/gl\&.h>\fP
.br
\fC#include <GL/glut\&.h>\fP
.br
\fC#include 'gam\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOLUMNS\fP   40"
.br
.ti -1c
.RI "#define \fBROWS\fP   40"
.br
.ti -1c
.RI "#define \fBFPS\fP   10"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplay_callback\fP ()"
.br
.ti -1c
.RI "void \fBtimer_callback\fP (int)"
.br
.ti -1c
.RI "void \fBreshape_callback\fP (int, int)"
.br
.ti -1c
.RI "void \fBkeyboard_callback\fP (int, int, int)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBgameOver\fP =false"
.br
.ti -1c
.RI "short \fBsDirection\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COLUMNS   40"

.SS "#define FPS   10"

.SS "#define ROWS   40"

.SH "Function Documentation"
.PP 
.SS "void display_callback ()"

.SS "void init ()"

.SS "void keyboard_callback (int key, int, int)"

.SS "int main (int argc, char ** argv)"

.SS "void reshape_callback (int w, int h)"

.SS "void timer_callback (int)"

.SH "Variable Documentation"
.PP 
.SS "bool gameOver =false"

.SS "short sDirection\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Paper from the source code\&.
